---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-deployment
  labels:
    app: users
spec:
  replicas: 1
  selector:
    matchLabels:
      app: users
  template:
    metadata:
      labels:
        app: users
    spec:
      containers:
      - name: users
        image: 22i0837/lightstep-users:8baa841b902fc47a87f4534d16ac91b371ecbc59
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: users-service
spec:
  type: ClusterIP
  selector:
    app: users
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080