---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-deployment
  labels:
    app: users
spec:
  replicas: 1
  selector:
    matchLabels:
      app: users
  template:
    metadata:
      labels:
        app: users
    spec:
      containers:
      - name: users
        image: 22i0837/lightstep-users:ed4cb06b41be3bfe267ed29de2bc8dd7c4804e17
        ports:
        - containerPort: 8080
        env:
        - name: DBHOST
          value: "mongodb://mongo-service:27017"

---
apiVersion: v1
kind: Service
metadata:
  name: users-service
spec:
  type: ClusterIP
  selector:
    app: users
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
